### PR TITLE
Seirawan2880b

### PR DESCRIPTION
**Pull request by ceebo**
This is the same as the previous PR except I don't change the hashing method and I check that the king and rook do not clash with the gating square in Chess960 castlings.

The first two commits do not change the bench number. The last one does but hopefully it is correct.

### CODE REVIEW

**Comment by ianfab** [comment]
You apparently have very well thought through all of the special cases appearing in 960 castling. I have not found any issues in your code, but I was wondering whether a king or rook that did not change its position during castling should retain the right to gate a piece, and I guess no one has defined yet how to handle this. One could argue that the pieces have moved, since they were part of a move (e.g., over the board you normally touch the king first in chess960 even when castling in a way that the king does not move to a different square, since castling is a king move). I am unsure which way to handle these cases is more intuitive. To me, both interpretations make kind of sense.

**Comment by ceebo** [comment]
Interesting. I didn't know about the human rule for castling in chess960. With Kg1 and Rh1 I would just hop the rook over to f1 and not touch the king. I agree that both interpretations make sense but I guess somebody just needs to pick one.

The difference in complexity between the two interpretations is tiny. The best way I found to explain both interpretations is:

"A piece loses gating rights when it moves from its original square."

vs.

"A piece loses gating rights when it moves or is involved in castling."

**Comment by ianfab** [comment]
@ceebo Many players intuitively only move with the rook in such a situation, but in tournaments (I have played a couple of OTB chess960 tournaments) people will make use of the touch-move rule, because FIDE rules define castling as a king move, so if you touch the rook first you will be forced to make a rook move, i.e., no castling. If you want to castle in such a case (Kg1, Rh1), in my experience it is usually considered best practice to move your king back towards edge of the board (behind the g1 square), then move the rook, and then move back the king, in order to make castling unambiguous.

I do not have a strong preference for one of the interpretations either, so for now I would just stick with your implementation and merge it.

**Comment by ceebo** [comment]
I see. It will be easy to remove the code if removal of gating rights in those situations becomes the consensus.

Thanks for merging this. It should be noted that SEE is now a bit broken in the case of Queen gates. I will try to give you a patch for this a bit later. Also I have few small non-functional change tweaks in mind. After that it is hopefully just the "fun stuff" of teaching the engine how to play the game better.

**Comment by ianfab** [comment]
The SEE change for gating moves is anyway only kind of a hack, but the results in testing looked good, so I decided to add it. If S-Chess would be available in cutechess, we could also test on fishtest, but alwey was facing some issues with the implementation of S-Chess in cutechess, so I guess it will take some time. Running tests on fishtest is much more convenient than running the testing script locally, otherwise I would test much more patches for S-Chess.

**Pull request merged**
