### PR TITLE
Near SF9 merge

### PR DESCRIPTION
**Pull request by ceebo**
This gets the code close to SF9. Some of these commits had conflicts but didn't require any real thinking. Do you have any comments on these?

There are 5 commits that I left out either because they looked more difficult to merge or depended on another:

https://github.com/official-stockfish/Stockfish/commit/a87a1005ad63c8076a79ea3b2648f87fea49cfc5 --- Need to think of a way to implement this. I'm not a fan of creating an extra piece type.

https://github.com/official-stockfish/Stockfish/commit/196ae7c38b99e5e885d319b18a3b2538319de939 --- Should we include Hawk/Elephant in this logic or leave as just Queen?

https://github.com/official-stockfish/Stockfish/commit/020dd69a3512d01c7f189b1aea64fa75c7e1b7cd --- Quite a big commit. I didn't look at it hard.

https://github.com/official-stockfish/Stockfish/commit/be6fafd0793d934c31925832b4bde569b5abd5b9 --- Should be fine but conflicts with previous commit textually.

https://github.com/official-stockfish/Stockfish/commit/7d4d3a2c3a4c6ce96bdbcfecf373934fdccc9b07 --- Not complicated but should we include Hawk/Elephant too?

### CODE REVIEW

**Comment by ianfab** [comment]
@ceebo 
Thanks for bringing that up. I tried a merge a few weeks ago and even merged this "fake extra piece" commit, but I did not like it (to say the least) and there were further conflicts to resolve, so I postponed it. It sounds reasonable to not merge such problematic commits, even though that might further complicate future merges. I will try to have a look at the merge and the excluded commits, but the next days I will probably be too busy to give any feedback.

As a next step could you maybe submit a test (I'd say a few thousand games at LTC) to measure the Elo difference for this merge? That's mainly to do some basic check whether there might be a regressive patch that should be excluded/reverted or whether something might have went wrong during merging.

**Comment by ceebo** [comment]
@ianfab OK, I submitted a test. One thing that strikes me is the difference in the treatment of MoveOverhead after the revert of the time management. The old TM was happy to go down to MoveOverhead time on the clock after any move but the new one reserves MoveOverhead for every move that it plans ahead. I haven't done any measurements but I would guess if we keep MoveOverhead at 100 this will mean a few seconds time handicap in a 30+0.3 game.

**Comment by ianfab** [comment]
I did not follow the back and forth in the time management code closely enough to be able to give a qualified answer, but I am always open to suggestions for changing the default parameters if they are backed up by some data. Regarding time losses, crazyhouse proved to be the critical variant, so as long as the rate of time losses stays at a manageable level in crazyhouse, I would be ok with decreasing the default move overhead.

**Comment by ceebo** [comment]
I ran a 2000 games LTC test on these commits and the result was neutral:

http://35.161.250.236:6543/tests/view/5a748d376e23db0fbab0d373
```
ELO: 2.08 +-11.8 (95%) LOS: 63.6%
Total: 2000 W: 603 L: 591 D: 806
```

That is roughly to be expected considering there are just two SPRT[0,5] tests in the above series. Namely "Use mobility in king safety" and "Limit the king distance factor when evaluating passed pawns".

EDIT: It looks like Github has ordered the 4 later commits by the time that I authored them and not the time I made the push. The 2000 game test does not apply to these commits.

**Comment by ceebo** [comment]
I pushed another 4 commits that implement the 5 commits mentioned in the first post of this PR. The first commit corresponds to patches 3 and 4 in the first list. It is just a general refactoring that doesn't have much to do with Seirawan chess.

The other 3 patches all come from successful SPRT[0,5] patches to upstream SF. In particular the patch "Attack Threats" seemed strong so I tried hardest to "Seirawanise" that one. I did so without creating an extra piece type for QUEEN_DIAGONAL. The other 2 patches seemed less strong so I put one in un-Seirawanised and one I Seirawanised until I decided it would be ugly to go further.

The combination of these last 4 patches passed under the standard STC and LTC regime:

STC: http://35.161.250.236:6543/tests/view/5a75ff226e23db0fbab0d37c
LLR: 2.95 (-2.94,2.94) [0.00,10.00]
Total: 3006 W: 1054 L: 939 D: 1013

LTC: http://35.161.250.236:6543/tests/view/5a76110a6e23db0fbab0d37f
LLR: 2.97 (-2.94,2.94) [0.00,10.00]
Total: 2296 W: 765 L: 662 D: 869

I wonder what your thoughts are on this entire series (and on the somewhat haphazard testing method).

EDIT: Just for a data-point I should mention that I ran these two tests with the SF-default MoveOverhead of 30 and there were no time losses.

**Comment by ianfab** [comment]
So far I only had a look at the new commits and they mostly look good to be. I will try to review the rest in the next days, but since you said that these changes were not very problematic to merge, I guess they should anyway be fine. It is comforting that the test results for both parts are in very good agreement with the expectations.

I think that merging and testing in two parts made sense and I am glad that we are close to getting back in sync with upstream again. Great work.

**Comment by ceebo** [comment]
Yes, I took another look over the first batch of commits and nothing stands out as alarming. The only functional change that had a merge error was "Remove ThreatByHangingPawn bonus" and that was only because of a whitespace difference. All of the other conflicts were in non-functional change patches such as the constexpr changes to types.h.

I'm pleased that the second batch of commits passed SPRT[0,10]. I suppose I made some debatable decisions when choosing how to implement them in Seirawan. In official-stockfish some time would be spent trying to prove that each patch was being committed in its minimal form but I don't think that is practical here.

**Comment by ianfab** [comment]
Yes, practicality is more important here than saving a few code lines. We can still try to simplify it away later if code turns out to not gain any Elo.

**Pull request merged**
